# Assignment 16 :

In [ ]:
# 1. What is a Python library? Why do we use Python libraries? 
a collection of related modules that contain bundles of codes that can be used in different programs. 

In [ ]:
# 2. What is the difference between Numpy array and List? 
"numpy is much faster in comparision to list"

In [1]:
import numpy as np

In [16]:
# 3. Find the shape, size and dimension of the following array? arr=[[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]]
  
arr=[[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]]
print('shape of arr :',np.shape(arr))
print('size of arr :',np.size(arr))
print('dimension of arr :',np.ndim(arr))

shape of arr : (3, 4)
size of arr : 12
dimension of arr : 2


In [18]:
# 4. Write python co^e to access the first row of the following array?  arr = [[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]]
    
arr = [[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]]
arr[0]

[1, 2, 3, 4]

In [24]:
# 5. How ^o you access the element at the thir^ row an^ fourth column from the given numpy array? arr=[[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]]
    
arr=[[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]]
arr[2:3]

[[9, 10, 11, 12]]

In [26]:
# 6. Write co^e to extract all o^^-in^exe^ elements from the given numpy array?  arr = [[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]]

arr = [[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]]
d=[]
for i in arr:
    for j in i:  
        if j%2!=0:
            d.append(j)
d

[1, 3, 5, 7, 9, 11]

In [37]:
# 7. How can you generate a ran^om 3x3 matrix with values between 0 an^ 1?

np.linspace(0,1,9).reshape(3,3)

array([[0.   , 0.125, 0.25 ],
       [0.375, 0.5  , 0.625],
       [0.75 , 0.875, 1.   ]])

In [35]:
# 8. Describe the ^ifference between np.ran^om.ran^ an^ np.ran^om.ran^n?
the major difference between np.random.randint and np.random.randn is that np.random.randn is used to generate normally distributed data 

In [39]:
# 9. Write co^e to increase the ^imension of the following array? arr = [[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]]
arr = [[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]]
np.expand_dims(arr,axis=1)

array([[[ 1,  2,  3,  4]],

       [[ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12]]])

In [54]:
# 10. How to transpose the following array in NumPy? arr = [[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]]
arr = np.arange(1,13).reshape(3,4)
arr.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [79]:
# 11. '''Consi^er the following matrix: Matrix A2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]] Matrix B2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]] Perform the following operation using Python1 ,+ I(dex wiLe multiplicatio' ]+ Matix multiplicatio' + Add both the maticK -+ Subtact matix B om  + Diide Matix B by A'''
a= np.arange(1,13).reshape(3,4)
b= np.arange(1,13).reshape(3,4)
print(a+b)
print(a*b)
print(a-b)
print(a@b.T)
print(a//b)

[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]
[[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[ 30  70 110]
 [ 70 174 278]
 [110 278 446]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [ ]:
# 12. Which function in Numpy can be used to swap the byte order of an array?
 newbyteorder() can be used to swap the byte order of an array

In [ ]:
# 13. What is the significance of the np.linalg.inv function?
to calculate the inverse of a matrix.

In [ ]:
# 14. What ^oes the np.reshape function ^o, an^ how is it use^?
it reshapes the the dimension of the array

In [82]:
# 15. What is broa^casting in Numpy?
'an operation of matching the dimensions of differently shaped arrays in order to be able to perform further operations on those arrays'

'an operation of matching the dimensions of differently shaped arrays in order to be able to perform further operations on those arrays'